### ISSUE TITLE
Is it OK to change the CSS?

### ISSUE THREAD

**Issue by oo-meg-oo** [Jack-McCourt/css3-animate-it#20]
Hi!
Thank you for the plugin!
I have a question.
Is it OK to change the animation speed in CSS?
(something like; 1.5s to 1.8s)
I want to change the fadeIn speed a little bit.
I am not gonna change the js file.

I am from Japan so I am sorry my poor English and stupid question.

**Comment by Jack-McCourt** [comment]
No problem at all, you can change what you like :)
