### ISSUE TITLE
Blank space on swipe (chrome)

### ISSUE THREAD

**Issue by vienzent** [Jack-McCourt/css3-animate-it#3]
there is a blanck space when you swipe right to left.

**Comment by amanbhatnagar2013** [comment]
yes me also having the same problem.. Even when i open your website on ipad or smartphone , it shows white blank space when swipe right to left..i love this 'animate-it' but if you will resolve this will be very thankful

**Comment by nrvnm** [comment]
Hey guys, I have the same problem too. It looks like animation types "anything that involves flying out from the side of the website" (particularly from the right side) are just moved to far right and hidden, so the body gets wider and huge white vertical stripe appear on the right side.

A quick hack for this is to overflow: hidden for the container of "flying" element. Don't do this on <body> though.

@Jack-McCourt ? Any thought on how to fix this? I've seen you have <body> tag with overflow: hidden on you animate it example page... not a finest solution.

**Comment by jack-planys** [comment]
Hi Guys,
I need to get round to doing an update at some point however yes the solution I have been using has been to apply overflow:hidden. Im not sure why you see this as "not a finest solution", if you have a better solution then feel free to contribute and I will add it to the plugin.

**Comment by nrvnm** [comment]
No offense, I think overflow-x and -y are still kind of experimental. Unfortunately I'm not a real coder, just learning. On my website I can't use overflow to solve this, guess just will have to reorganize things somehow, or change animation to something "not flying" like growIn or fadeIn.

**Comment by banchee** [comment]
my solution to this, 

override the `.animatedParent` css class to include `override: hidden`

Works like charm

**Comment by VImpe** [comment]
this is not a perfect solution but help at time of resize screen of brawser

function createLinkTag(){
            var link = document.createElement('link');
            link.id = 'animation-id';
            link.rel = 'stylesheet';
            link.href="<?php echo $GLOBALS['cdn']; ?>/lib/css/b2b-animations-v1.0.css";
            document.getElementById('animatePage').appendChild(link);
        }
        createLinkTag();
       $(window).resize(function(){
           var element = document.getElementById("animation-id");
           element.parentNode.removeChild(element);
           setTimeout(function(){
               createLinkTag();

           },1000);
        })

**Comment by jimmyadaro** [comment]
@banchee Not working on Safari. I've tried this but still **not working**.

```
.animatedParent {
	overflow: hidden;
 	overflow-x: hidden;
 	overflow-y: hidden;
}

**Comment by jimmyadaro** [comment]
@Jack-McCourt Why has been this issue closed? Where is the solution for this?
