### ISSUE TITLE
blank without scroll

### ISSUE THREAD

**Issue by abhikhatri** [Jack-McCourt/css3-animate-it#6]
Well I am using animate it to my hero image elements but whenever i refresh the page, the hero image stays blank until i scroll the page, what should I do?

Do you have any classes to animate it as soon as the page loads?

**Comment by jack-planys** [comment]
It should animate on page load, do you have a link to the page so I can possibly see whats causing it?

**Comment by abhikhatri** [comment]
I am using data-sequence= 500
is it causing that??
I can give u a screenshot cause it's not yet public

**Comment by abhikhatri** [comment]
Oh i find the bug, there was a bug in my rails code, It just works like charm now. 

Thanks man for this awesome tool, I really really loved it.
